# Generated by Django 4.1.5 on 2023-01-21 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'yangilanish'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AddField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 1, 21, 17, 56, 43, 161026), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
