# Generated by Django 4.1.5 on 2023-01-26 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_contactus_alter_student_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cover_img', models.ImageField(upload_to='category')),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoriya',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 18, 0, 10, 779060), null=True),
        ),
    ]
