# Generated by Django 4.1.5 on 2023-02-07 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_cover_img_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 2, 7, 17, 14, 32, 769618), null=True),
        ),
    ]
