# Generated by Django 4.1.6 on 2023-02-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_contactus_student_todo_complated_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 17, 2, 21, 78052), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='complated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
