# Generated by Django 4.1.6 on 2023-02-14 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0003_alter_student_birthday_alter_todo_complated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 17, 10, 3, 174041), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
