# Generated by Django 4.1.7 on 2023-02-17 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('fee', models.FloatField(default=0)),
                ('roll_no', models.IntegerField(unique=True)),
                ('addres', models.TextField()),
                ('is_registered', models.BooleanField(default=False)),
                ('birthDay', models.DateField(default=datetime.datetime(2023, 2, 17, 17, 18, 39, 554571), null=True)),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='sifat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('complated', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('sifati', 'namunali'), ('sifati', 'yaxshi'), ('sifati', 'qoniqasiz')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
