# Generated by Django 4.1.7 on 2023-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='sifat',
            name='narxi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
