# Generated by Django 4.1.7 on 2023-02-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_card', '0002_delete_student_sifat_narxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sifat',
            name='narxi',
        ),
    ]
