# Generated by Django 4.1.5 on 2023-01-24 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_student_alter_post_pst_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_add', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AddField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 17, 7, 12, 585180), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='addres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='akkauntungizni kiriting'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='F,I,O'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=50, verbose_name='ayol v erkak'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Telefon raqam'),
        ),
    ]
